title = "Norbert"
theme = "d3c3nt"
base_url = "https://bitnorbert.com"
compile_sass = true
build_search_index = false

[markdown]
highlight_code = false

[extra]
sam_menu = [
    { text = "about", link = "/about" },
    { text = "twitter", link = "https://twitter.com/bitnorbert" },
    { text = "github", link = "https://github.com/bitnorbert" }
]

show_word_count = false
show_reading_time = false

d3_nav = [
  { name = "HOME", path = "/" },
  { name = "TWITTER", path = "https://twitter.com/bitnorbert" }
]
